from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import pipeline_cli  # type: ignore
from pipeline_registry import get_pipeline  # type: ignore


def test_build_megaminx_prompt_context_includes_real_bundle_facts_and_examples():
    spec = get_pipeline('cayley-py-megaminx')
    context = pipeline_cli._build_competition_prompt_context(spec)

    assert 'AUTOGENERATED COMPETITION CONTEXT' in context
    assert 'central_state length: 120' in context
    assert 'total legal move tokens in puzzle_info.json: 24' in context
    assert 'forward face names (12):' in context
    assert 'test row count: 1001' in context
    assert 'sample submission row count: 1001' in context
    assert 'score_original=500572' in context
    assert 'score_optimized=416067' in context
    assert 'row 100 / initial_state_id=100' in context
    assert 'row 943 / initial_state_id=943' in context


def test_materialized_megaminx_prompt_appends_context_to_base_prompt():
    spec = get_pipeline('cayley-py-megaminx')
    prompt_file = ROOT / 'competitions' / 'cayley-py-megaminx' / 'prompts' / 'user_prompt_improved.txt'
    base_text = prompt_file.read_text(encoding='utf-8')

    with pipeline_cli._materialize_prompt_with_competition_context(spec, prompt_file) as materialized:
        materialized_text = Path(materialized).read_text(encoding='utf-8')

    assert materialized_text.startswith(base_text.rstrip())
    assert 'AUTOGENERATED COMPETITION CONTEXT' in materialized_text
    assert 'EXAMPLES FROM THE ACTUAL BUNDLE' in materialized_text


def test_cmd_generate_solver_passes_augmented_megaminx_prompt(monkeypatch, tmp_path):
    captured = {}

    def fake_run_agent_laboratory(**kwargs):
        captured['prompt_text'] = Path(kwargs['prompt_file']).read_text(encoding='utf-8')
        Path(kwargs['out_path']).write_text('def solve(vec):\n    return [], list(vec)\n', encoding='utf-8')

    def fake_validate_solver(*args, **kwargs):
        return None

    monkeypatch.setattr(pipeline_cli, '_run_agent_laboratory', fake_run_agent_laboratory)
    monkeypatch.setattr(pipeline_cli, '_validate_solver', fake_validate_solver)
    monkeypatch.setattr(pipeline_cli, '_gpu_diag_hint', lambda *_a, **_k: None)

    args = type('Args', (), {})()
    args.competition = 'cayley-py-megaminx'
    args.out = str(tmp_path / 'generated_solver.py')
    args.prompt_file = None
    args.custom_prompts = None
    args.prompt_variant = 'improved'
    args.no_llm = False
    args.models = 'gpt-4o-mini'
    args.agent_models = None
    args.planner_models = None
    args.coder_models = None
    args.fixer_models = None
    args.search_mode = None
    args.plan_beam_width = None
    args.frontier_width = None
    args.archive_size = None
    args.refine_rounds = None
    args.max_iters = 2
    args.allow_baseline = True
    args.g4f_recovery_rounds = None
    args.g4f_recovery_max_iters = None
    args.g4f_recovery_sleep = None
    args.worker_no_kill_process_group = False
    args.print_generation = False
    args.print_generation_max_chars = None
    args.g4f_async = None
    args.max_response_chars = None
    args.g4f_request_timeout = None
    args.g4f_stop_at_python_fence = None

    pipeline_cli.cmd_generate_solver(args)

    assert 'AUTOGENERATED COMPETITION CONTEXT' in captured['prompt_text']
    assert 'row 943 / initial_state_id=943' in captured['prompt_text']
    assert 'optimized_stats.json reports score_original=500572' in captured['prompt_text']
